coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%

flags:
  extension:
    paths:
      - src/
    carryforward: true
  webview:
    paths:
      - webview/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
