# Netlify configuration for Datalayer VS Code Extension documentation
# Automatically builds TypeDoc documentation on every push to main branch

[build]
  # Build command (use npm install since package-lock.json is not committed)
  command = "npm install && npm run doc"
  # Publish directory (TypeDoc output)
  publish = "docs/"

[build.processing]
  # Skip processing since TypeDoc generates static HTML
  skip_processing = false

[build.processing.css]
  # Bundle CSS for faster loading
  bundle = true
  minify = true

[build.processing.js]
  # Bundle and minify JavaScript
  bundle = true
  minify = true

[build.processing.html]
  # Pretty URLs for better UX
  pretty_urls = true

# Branch-specific build settings
[context.production]
  command = "npm install && npm run doc"

[context.deploy-preview]
  command = "npm install && npm run doc"

[context.branch-deploy]
  command = "npm install && npm run doc"

# Custom headers for documentation
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"


# Security and performance
[build.environment]
  # NOTE: Do NOT set NODE_ENV = "production" here!
  # It prevents devDependencies from being installed, breaking patch-package and typedoc
  NODE_VERSION = "20"
  GENERATE_SOURCEMAP = "false"
  CI = "true"
  # Increase Node.js heap size for large documentation builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Skip Husky hooks in CI
  HUSKY = "0"
  # Disable npm update notifier
  NO_UPDATE_NOTIFIER = "1"
  # Disable npm funding messages
  OPEN_SOURCE_CONTRIBUTOR = "1"

